apiVersion: v1
kind: Service
metadata:
  name: smart-appointment-frontend
spec:
  type: NodePort
  selector:
    app: smart-appointment-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
